import 'package:flutter/material.dart';

class SystemModel {
  final String id;
  final String name;
  final String manufacturer;
  final int releaseYear;
  final bool isZipped;
  final String libretroId;
  final List<String> romExtensions;
  final String iconName;
  final Color accentColor;
  final List<String>? multiFileExtensions;
  final int? raConsoleId;

  /// Whether a game that is stored as a folder is saved as one `.zip` by
  /// default: this system's emulator installs games from an archive and
  /// cannot use a loose folder.
  final bool packFolderGames;

  const SystemModel({
    required this.id,
    required this.name,
    required this.manufacturer,
    required this.releaseYear,
    this.isZipped = true,
    this.libretroId = '',
    this.romExtensions = const [],
    this.iconName = '',
    this.accentColor = Colors.redAccent,
    this.multiFileExtensions,
    this.raConsoleId,
    this.packFolderGames = false,
  });

  /// Whether this system has RetroAchievements support.
  bool get hasRetroAchievements => raConsoleId != null;

  /// Returns the local asset path for this system's icon.
  String get iconAssetPath => 'assets/platform_icons/$iconName';

  /// Returns a color suitable for icon tinting on dark backgrounds.
  /// Ensures minimum luminance so icons stay visible.
  Color get iconColor {
    final luminance = accentColor.computeLuminance();
    if (luminance >= 0.15) return accentColor;
    final hsl = HSLColor.fromColor(accentColor);
    return hsl.withLightness(hsl.lightness.clamp(0.45, 1.0)).toColor();
  }

  /// Accent color with enough contrast for text on dark backgrounds.
  /// Higher luminance floor than [iconColor] for small text readability.
  Color get textAccentColor {
    final luminance = accentColor.computeLuminance();
    if (luminance >= 0.2) return accentColor;
    final hsl = HSLColor.fromColor(accentColor);
    return hsl.withLightness(hsl.lightness.clamp(0.55, 1.0)).toColor();
  }

  static const List<SystemModel> supportedSystems = [
    // ===== NINTENDO =====
    SystemModel(
      id: 'nes',
      name: 'Nintendo Entertainment System',
      manufacturer: 'Nintendo',
      releaseYear: 1983,
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_Entertainment_System',
      romExtensions: ['.nes'],
      iconName: 'nintendo_nes.svg',
      accentColor: Color(0xFFE11D48),
      raConsoleId: 7,
    ),
    SystemModel(
      id: 'snes',
      name: 'Super Nintendo',
      manufacturer: 'Nintendo',
      releaseYear: 1990,
      isZipped: true,
      libretroId: 'Nintendo_-_Super_Nintendo_Entertainment_System',
      romExtensions: ['.sfc', '.smc'],
      iconName: 'nintendo_snes.svg',
      accentColor: Color(0xFF9333EA),
      raConsoleId: 3,
    ),
    SystemModel(
      id: 'n64',
      name: 'Nintendo 64',
      manufacturer: 'Nintendo',
      releaseYear: 1996,
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_64',
      romExtensions: ['.z64', '.n64', '.v64'],
      iconName: 'nintendo_64.svg',
      accentColor: Color(0xFFF97316),
      raConsoleId: 2,
    ),
    SystemModel(
      id: 'gc',
      name: 'Nintendo GameCube',
      manufacturer: 'Nintendo',
      releaseYear: 2001,
      isZipped: false,
      libretroId: 'Nintendo_-_GameCube',
      romExtensions: ['.rvz', '.iso', '.gcm', '.ciso'],
      iconName: 'nintendo_gamecube.svg',
      accentColor: Color(0xFF7C3AED),
      raConsoleId: 16,
    ),
    SystemModel(
      id: 'wii',
      name: 'Nintendo Wii',
      manufacturer: 'Nintendo',
      releaseYear: 2006,
      isZipped: false,
      libretroId: 'Nintendo_-_Wii',
      romExtensions: ['.rvz', '.wbfs', '.iso', '.wia', '.ciso'],
      iconName: 'nintendo_wii.svg',
      accentColor: Color(0xFF0EA5E9),
      raConsoleId: 19,
    ),
    SystemModel(
      id: 'wiiu',
      name: 'Nintendo Wii U',
      manufacturer: 'Nintendo',
      releaseYear: 2012,
      isZipped: false,
      libretroId: 'Nintendo_-_Wii_U',
      romExtensions: ['.wua', '.wud', '.wux', '.rpx'],
      iconName: 'nintendo_wiiu.svg',
      accentColor: Color(0xFF0284C7),
      raConsoleId: 20,
    ),
    SystemModel(
      id: 'switch',
      name: 'Nintendo Switch',
      manufacturer: 'Nintendo',
      releaseYear: 2017,
      isZipped: false,
      libretroId: 'Nintendo_-_Switch',
      romExtensions: ['.nsp', '.xci'],
      iconName: 'nintendo_switch.svg',
      accentColor: Color(0xFFE60012),
    ),
    SystemModel(
      id: 'gb',
      name: 'Game Boy',
      manufacturer: 'Nintendo',
      releaseYear: 1989,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy',
      romExtensions: ['.gb'],
      iconName: 'nintendo_gameboy.svg',
      accentColor: Color(0xFF8BAC0F),
      raConsoleId: 4,
    ),
    SystemModel(
      id: 'gbc',
      name: 'Game Boy Color',
      manufacturer: 'Nintendo',
      releaseYear: 1998,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy_Color',
      romExtensions: ['.gbc', '.gb'],
      iconName: 'nintendo_gameboy_color.svg',
      accentColor: Color(0xFF06B6D4),
      raConsoleId: 6,
    ),
    SystemModel(
      id: 'gba',
      name: 'Game Boy Advance',
      manufacturer: 'Nintendo',
      releaseYear: 2001,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy_Advance',
      romExtensions: ['.gba'],
      iconName: 'nintendo_gameboy_advance.svg',
      accentColor: Color(0xFF4F46E5),
      raConsoleId: 5,
    ),
    SystemModel(
      id: 'nds',
      name: 'Nintendo DS',
      manufacturer: 'Nintendo',
      releaseYear: 2004,
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_DS',
      romExtensions: ['.nds'],
      iconName: 'nintendo_ds.svg',
      accentColor: Color(0xFF6B7280),
      raConsoleId: 18,
    ),
    SystemModel(
      id: 'virtualboy',
      name: 'Virtual Boy',
      manufacturer: 'Nintendo',
      releaseYear: 1995,
      isZipped: true,
      libretroId: 'Nintendo_-_Virtual_Boy',
      romExtensions: ['.vb'],
      iconName: 'nintendo_virtualboy.svg',
      accentColor: Color(0xFFEF4444),
      raConsoleId: 28,
    ),
    SystemModel(
      id: 'fds',
      name: 'Famicom Disk System',
      manufacturer: 'Nintendo',
      releaseYear: 1986,
      isZipped: true,
      libretroId: 'Nintendo_-_Family_Computer_Disk_System',
      romExtensions: ['.fds'],
      iconName: 'nintendo_famicom_disksystem.svg',
      accentColor: Color(0xFFEF4444),
      raConsoleId: 81,
    ),
    SystemModel(
      id: 'dsi',
      name: 'Nintendo DSi',
      manufacturer: 'Nintendo',
      releaseYear: 2008,
      isZipped: false,
      libretroId: 'Nintendo_-_Nintendo_DSi',
      romExtensions: ['.nds', '.dsi', '.app'],
      iconName: 'nintendo_dsi.svg',
      accentColor: Color(0xFF94A3B8),
      raConsoleId: 78,
    ),
    SystemModel(
      id: 'n3ds',
      name: 'Nintendo 3DS',
      manufacturer: 'Nintendo',
      releaseYear: 2011,
      isZipped: false,
      libretroId: 'Nintendo_-_Nintendo_3DS',
      romExtensions: ['.3ds', '.cia', '.cci', '.cxi', '.app'],
      iconName: 'nintendo_3ds.svg',
      accentColor: Color(0xFFDC2626),
      raConsoleId: 62,
    ),
    // ===== SONY =====
    SystemModel(
      id: 'psx',
      name: 'PlayStation',
      manufacturer: 'Sony',
      releaseYear: 1994,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation',
      romExtensions: ['.chd', '.pbp', '.cue', '.iso', '.img'],
      iconName: 'playstation_flat.svg',
      accentColor: Color(0xFF5B21B6),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 12,
    ),
    SystemModel(
      id: 'ps2',
      name: 'PlayStation 2',
      manufacturer: 'Sony',
      releaseYear: 2000,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_2',
      romExtensions: ['.iso', '.chd', '.cso'],
      iconName: 'playstation_ps2.svg',
      accentColor: Color(0xFF1E3A8A),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 21,
    ),
    SystemModel(
      id: 'ps3',
      name: 'PlayStation 3',
      manufacturer: 'Sony',
      releaseYear: 2006,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_3',
      romExtensions: ['.iso', '.pkg'],
      iconName: 'playstation3_flat.svg',
      accentColor: Color(0xFF1E293B),
    ),
    // A game is a folder on the server (its .pkg files, or an unpacked dump
    // with eboot.bin), kept as a folder on download.
    SystemModel(
      id: 'ps4',
      name: 'PlayStation 4',
      manufacturer: 'Sony',
      releaseYear: 2013,
      isZipped: false,
      romExtensions: ['.pkg'],
      multiFileExtensions: ['.pkg', '.bin', '.ps4'],
      iconName: 'playstation4_flat.svg',
      accentColor: Color(0xFF003791),
    ),
    SystemModel(
      id: 'psp',
      name: 'PlayStation Portable',
      manufacturer: 'Sony',
      releaseYear: 2004,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_Portable',
      romExtensions: ['.iso', '.cso', '.pbp', '.chd'],
      iconName: 'playstation_psp.svg',
      accentColor: Color(0xFF475569),
      raConsoleId: 41,
    ),
    SystemModel(
      id: 'psvita',
      name: 'PlayStation Vita',
      manufacturer: 'Sony',
      releaseYear: 2011,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_Vita',
      romExtensions: ['.vpk'],
      // Vita3K installs from .zip/.vpk; it has no use for a loose folder.
      packFolderGames: true,
      iconName: 'playstation_vita.svg',
      accentColor: Color(0xFF1E40AF),
    ),
    // ===== SEGA =====
    SystemModel(
      id: 'mastersystem',
      name: 'Master System',
      manufacturer: 'Sega',
      releaseYear: 1985,
      isZipped: true,
      libretroId: 'Sega_-_Master_System_-_Mark_III',
      romExtensions: ['.sms'],
      iconName: 'sega_master_system.svg',
      accentColor: Color(0xFF1D4ED8),
      raConsoleId: 11,
    ),
    SystemModel(
      id: 'megadrive',
      name: 'Mega Drive',
      manufacturer: 'Sega',
      releaseYear: 1988,
      isZipped: true,
      libretroId: 'Sega_-_Mega_Drive_-_Genesis',
      romExtensions: ['.md', '.gen', '.bin', '.smd'],
      iconName: 'sega_megadrive.svg',
      accentColor: Color(0xFF374151),
      raConsoleId: 1,
    ),
    SystemModel(
      id: 'gamegear',
      name: 'Game Gear',
      manufacturer: 'Sega',
      releaseYear: 1990,
      isZipped: true,
      libretroId: 'Sega_-_Game_Gear',
      romExtensions: ['.gg'],
      iconName: 'sega_gamegear.svg',
      accentColor: Color(0xFF0F766E),
      raConsoleId: 15,
    ),
    SystemModel(
      id: 'segacd',
      name: 'Sega CD',
      manufacturer: 'Sega',
      releaseYear: 1991,
      isZipped: false,
      libretroId: 'Sega_-_Mega-CD_-_Sega_CD',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'sega_cd.svg',
      accentColor: Color(0xFF0369A1),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 9,
    ),
    SystemModel(
      id: 'sega32x',
      name: 'Sega 32X',
      manufacturer: 'Sega',
      releaseYear: 1994,
      isZipped: true,
      libretroId: 'Sega_-_32X',
      romExtensions: ['.32x'],
      iconName: 'sega_32x.svg',
      accentColor: Color(0xFF991B1B),
      raConsoleId: 10,
    ),
    SystemModel(
      id: 'dreamcast',
      name: 'Dreamcast',
      manufacturer: 'Sega',
      releaseYear: 1998,
      isZipped: false,
      libretroId: 'Sega_-_Dreamcast',
      romExtensions: ['.chd', '.cdi', '.gdi'],
      iconName: 'sega_dreamcast.svg',
      accentColor: Color(0xFFDC2626),
      raConsoleId: 40,
    ),
    SystemModel(
      id: 'saturn',
      name: 'Saturn',
      manufacturer: 'Sega',
      releaseYear: 1994,
      isZipped: false,
      libretroId: 'Sega_-_Saturn',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'sega_saturn.svg',
      accentColor: Color(0xFF64748B),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 39,
    ),
    SystemModel(
      id: 'sg1000',
      name: 'SG-1000',
      manufacturer: 'Sega',
      releaseYear: 1983,
      isZipped: true,
      libretroId: 'Sega_-_SG-1000',
      romExtensions: ['.sg', '.sc'],
      iconName: 'sega_sg1000.svg',
      accentColor: Color(0xFF3B82F6),
      raConsoleId: 33,
    ),
    // ===== NEC =====
    SystemModel(
      id: 'tg16',
      name: 'TurboGrafx-16',
      manufacturer: 'NEC',
      releaseYear: 1987,
      isZipped: true,
      libretroId: 'NEC_-_PC_Engine_-_TurboGrafx_16',
      romExtensions: ['.pce'],
      iconName: 'nec_turbografx16.svg',
      accentColor: Color(0xFF0891B2),
      raConsoleId: 8,
    ),
    SystemModel(
      id: 'tgcd',
      name: 'TurboGrafx-CD',
      manufacturer: 'NEC',
      releaseYear: 1989,
      isZipped: false,
      libretroId: 'NEC_-_PC_Engine_CD_-_TurboGrafx-CD',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'nec_turbografxcd.svg',
      accentColor: Color(0xFF0E7490),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 76,
    ),
    // ===== SNK =====
    SystemModel(
      id: 'ngp',
      name: 'Neo Geo Pocket',
      manufacturer: 'SNK',
      releaseYear: 1998,
      isZipped: true,
      libretroId: 'SNK_-_Neo_Geo_Pocket',
      romExtensions: ['.ngp', '.ngc'],
      iconName: 'snk_neogeo_pocket.svg',
      accentColor: Color(0xFFCA8A04),
      raConsoleId: 14,
    ),
    SystemModel(
      id: 'neogeocd',
      name: 'Neo Geo CD',
      manufacturer: 'SNK',
      releaseYear: 1994,
      isZipped: false,
      libretroId: 'SNK_-_Neo_Geo_CD',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'snk_neogeo_cd.svg',
      accentColor: Color(0xFFEAB308),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 56,
    ),
    // ===== BANDAI =====
    SystemModel(
      id: 'wonderswan',
      name: 'WonderSwan',
      manufacturer: 'Bandai',
      releaseYear: 1999,
      isZipped: true,
      libretroId: 'Bandai_-_WonderSwan',
      romExtensions: ['.ws', '.wsc'],
      iconName: 'bandai_wonderswan.svg',
      accentColor: Color(0xFF2563EB),
      raConsoleId: 53,
    ),
    // ===== COLECO =====
    SystemModel(
      id: 'colecovision',
      name: 'ColecoVision',
      manufacturer: 'Coleco',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'Coleco_-_ColecoVision',
      romExtensions: ['.col'],
      iconName: 'coleco_vision.svg',
      accentColor: Color(0xFF3B82F6),
      raConsoleId: 44,
    ),
    // ===== MATTEL =====
    SystemModel(
      id: 'intellivision',
      name: 'Intellivision',
      manufacturer: 'Mattel',
      releaseYear: 1979,
      isZipped: true,
      libretroId: 'Mattel_-_Intellivision',
      romExtensions: ['.int'],
      iconName: 'mattel_intellivision.svg',
      accentColor: Color(0xFFD97706),
      raConsoleId: 45,
    ),
    // ===== GCE =====
    SystemModel(
      id: 'vectrex',
      name: 'Vectrex',
      manufacturer: 'GCE',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'GCE_-_Vectrex',
      romExtensions: ['.vec'],
      iconName: 'vectrex.svg',
      accentColor: Color(0xFF10B981),
      raConsoleId: 46,
    ),
    // ===== MICROSOFT =====
    SystemModel(
      id: 'msx',
      name: 'MSX',
      manufacturer: 'Microsoft',
      releaseYear: 1983,
      isZipped: true,
      libretroId: 'Microsoft_-_MSX',
      romExtensions: ['.rom', '.mx1', '.mx2', '.dsk'],
      iconName: 'msx.svg',
      accentColor: Color(0xFF7C3AED),
      raConsoleId: 29,
    ),
    // ===== AMSTRAD =====
    SystemModel(
      id: 'amstradcpc',
      name: 'Amstrad CPC',
      manufacturer: 'Amstrad',
      releaseYear: 1984,
      isZipped: true,
      libretroId: 'Amstrad_-_CPC',
      romExtensions: ['.dsk', '.cdt', '.sna'],
      iconName: 'amstrad_cpc.svg',
      accentColor: Color(0xFFDC2626),
      raConsoleId: 37,
    ),
    // ===== FAIRCHILD =====
    SystemModel(
      id: 'channelf',
      name: 'Fairchild Channel F',
      manufacturer: 'Fairchild',
      releaseYear: 1976,
      isZipped: true,
      libretroId: 'Fairchild_-_Channel_F',
      romExtensions: ['.bin', '.chf'],
      iconName: 'fairchild_channelf.svg',
      accentColor: Color(0xFFEA580C),
      raConsoleId: 57,
    ),
    // ===== MAGNAVOX =====
    SystemModel(
      id: 'odyssey2',
      name: 'Magnavox Odyssey 2',
      manufacturer: 'Magnavox',
      releaseYear: 1978,
      isZipped: true,
      libretroId: 'Magnavox_-_Odyssey2',
      romExtensions: ['.bin'],
      iconName: 'magnavox_odyssey2.svg',
      accentColor: Color(0xFF78716C),
      raConsoleId: 23,
    ),
    // ===== ATARI =====
    SystemModel(
      id: 'jaguar',
      name: 'Atari Jaguar',
      manufacturer: 'Atari',
      releaseYear: 1993,
      isZipped: true,
      libretroId: 'Atari_-_Jaguar',
      romExtensions: ['.j64', '.jag'],
      iconName: 'atari_jaguar.svg',
      accentColor: Color(0xFFDC2626),
      raConsoleId: 17,
    ),
    SystemModel(
      id: 'atari2600',
      name: 'Atari 2600',
      manufacturer: 'Atari',
      releaseYear: 1977,
      isZipped: true,
      libretroId: 'Atari_-_2600',
      romExtensions: ['.a26', '.bin'],
      iconName: 'atari_2600.svg',
      accentColor: Color(0xFFD97706),
      raConsoleId: 25,
    ),
    SystemModel(
      id: 'atari5200',
      name: 'Atari 5200',
      manufacturer: 'Atari',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'Atari_-_5200',
      romExtensions: ['.a52', '.bin'],
      iconName: 'atari_5200.svg',
      accentColor: Color(0xFF78716C),
      raConsoleId: 50,
    ),
    SystemModel(
      id: 'atari7800',
      name: 'Atari 7800',
      manufacturer: 'Atari',
      releaseYear: 1986,
      isZipped: true,
      libretroId: 'Atari_-_7800',
      romExtensions: ['.a78', '.bin'],
      iconName: 'atari_7800.svg',
      accentColor: Color(0xFF6B7280),
      raConsoleId: 51,
    ),
    SystemModel(
      id: 'lynx',
      name: 'Atari Lynx',
      manufacturer: 'Atari',
      releaseYear: 1989,
      isZipped: true,
      libretroId: 'Atari_-_Lynx',
      romExtensions: ['.lnx'],
      iconName: 'atari_lynx.svg',
      accentColor: Color(0xFF059669),
      raConsoleId: 13,
    ),
    SystemModel(
      id: 'jaguarcd',
      name: 'Atari Jaguar CD',
      manufacturer: 'Atari',
      releaseYear: 1995,
      isZipped: false,
      libretroId: 'Atari_-_Jaguar_CD',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'atari_jaguarcd.svg',
      accentColor: Color(0xFFDC2626),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 77,
    ),
    SystemModel(
      id: 'atarist',
      name: 'Atari ST',
      manufacturer: 'Atari',
      releaseYear: 1985,
      isZipped: true,
      libretroId: 'Atari_-_ST',
      romExtensions: ['.st', '.stx', '.msa'],
      iconName: 'atari_st.svg',
      accentColor: Color(0xFF60A5FA),
      raConsoleId: 36,
    ),
    // ===== NEC (continued) =====
    SystemModel(
      id: 'pcfx',
      name: 'PC-FX',
      manufacturer: 'NEC',
      releaseYear: 1994,
      isZipped: false,
      libretroId: 'NEC_-_PC-FX',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'nec_pcfx.svg',
      accentColor: Color(0xFF0891B2),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 49,
    ),
    // ===== COMMODORE =====
    SystemModel(
      id: 'c64',
      name: 'Commodore 64',
      manufacturer: 'Commodore',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'Commodore_-_64',
      romExtensions: ['.d64', '.t64', '.tap', '.crt', '.prg'],
      iconName: 'commodore_64.svg',
      accentColor: Color(0xFFD97706),
      raConsoleId: 30,
    ),
    SystemModel(
      id: 'vic20',
      name: 'VIC-20',
      manufacturer: 'Commodore',
      releaseYear: 1980,
      isZipped: true,
      libretroId: 'Commodore_-_VIC-20',
      romExtensions: ['.d64', '.t64', '.tap', '.crt', '.prg'],
      iconName: 'commodore_vic20.svg',
      accentColor: Color(0xFF78716C),
      raConsoleId: 34,
    ),
    SystemModel(
      id: 'amiga',
      name: 'Amiga',
      manufacturer: 'Commodore',
      releaseYear: 1985,
      isZipped: true,
      libretroId: 'Commodore_-_Amiga',
      romExtensions: ['.adf', '.adz', '.dms', '.ipf', '.hdf', '.lha'],
      iconName: 'commodore_amiga.svg',
      accentColor: Color(0xFFDC2626),
      raConsoleId: 35,
    ),
    // ===== SINCLAIR =====
    SystemModel(
      id: 'zxspectrum',
      name: 'ZX Spectrum',
      manufacturer: 'Sinclair',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'Sinclair_-_ZX_Spectrum',
      romExtensions: ['.z80', '.tzx', '.tap', '.sna', '.dsk'],
      iconName: 'sinclair_zxspectrum.svg',
      accentColor: Color(0xFFDC2626),
      raConsoleId: 59,
    ),
    // ===== TANGERINE =====
    SystemModel(
      id: 'oric',
      name: 'Oric',
      manufacturer: 'Tangerine',
      releaseYear: 1983,
      isZipped: true,
      libretroId: 'Tangerine_Computer_Systems_-_Oric',
      romExtensions: ['.dsk', '.tap'],
      iconName: 'oric.svg',
      accentColor: Color(0xFFF97316),
      raConsoleId: 32,
    ),
    // ===== SHARP =====
    SystemModel(
      id: 'x68000',
      name: 'Sharp X68000',
      manufacturer: 'Sharp',
      releaseYear: 1987,
      isZipped: true,
      libretroId: 'Sharp_-_X68000',
      romExtensions: ['.dim', '.hdf', '.xdf', '.2hd', '.m3u'],
      iconName: 'sharp_x68000.svg',
      accentColor: Color(0xFF9CA3AF),
      raConsoleId: 52,
    ),
    SystemModel(
      id: 'x1',
      name: 'Sharp X1',
      manufacturer: 'Sharp',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'Sharp_-_X1',
      romExtensions: ['.dx1', '.2d', '.2hd', '.tap'],
      iconName: 'sharp_x1.svg',
      accentColor: Color(0xFF6B7280),
      raConsoleId: 64,
    ),
    // ===== FUJITSU =====
    SystemModel(
      id: 'fmtowns',
      name: 'FM Towns',
      manufacturer: 'Fujitsu',
      releaseYear: 1989,
      isZipped: false,
      libretroId: 'Fujitsu_-_FM_Towns',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'fujitsu_fmtowns.svg',
      accentColor: Color(0xFF2563EB),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 58,
    ),
    // ===== PHILIPS =====
    SystemModel(
      id: 'cdi',
      name: 'Philips CD-i',
      manufacturer: 'Philips',
      releaseYear: 1991,
      isZipped: false,
      libretroId: 'Philips_-_CDi',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: 'philips_cdi.svg',
      accentColor: Color(0xFF7C3AED),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 42,
    ),
    // ===== 3DO =====
    SystemModel(
      id: '3do',
      name: '3DO',
      manufacturer: '3DO Company',
      releaseYear: 1993,
      isZipped: false,
      libretroId: 'The_3DO_Company_-_3DO',
      romExtensions: ['.chd', '.cue', '.iso'],
      iconName: '3do.svg',
      accentColor: Color(0xFF059669),
      multiFileExtensions: ['.bin', '.cue'],
      raConsoleId: 43,
    ),
    // ===== APPLE =====
    SystemModel(
      id: 'appleii',
      name: 'Apple II',
      manufacturer: 'Apple',
      releaseYear: 1977,
      isZipped: true,
      libretroId: 'Apple_-_Apple_II',
      romExtensions: ['.dsk', '.do', '.po', '.nib', '.2mg'],
      iconName: 'apple-ii.svg',
      accentColor: Color(0xFF16A34A),
      raConsoleId: 38,
    ),
    // ===== NOKIA =====
    SystemModel(
      id: 'ngage',
      name: 'N-Gage',
      manufacturer: 'Nokia',
      releaseYear: 2003,
      isZipped: false,
      libretroId: 'Nokia_-_N-Gage',
      romExtensions: ['.app', '.sis'],
      iconName: 'nokia_ngage.svg',
      accentColor: Color(0xFF60A5FA),
      raConsoleId: 61,
    ),
    // ===== EMERSON =====
    SystemModel(
      id: 'arcadia2001',
      name: 'Arcadia 2001',
      manufacturer: 'Emerson',
      releaseYear: 1982,
      isZipped: true,
      libretroId: 'Emerson_-_Arcadia_2001',
      romExtensions: ['.bin'],
      iconName: 'emerson_arcadia.svg',
      accentColor: Color(0xFF78716C),
      raConsoleId: 73,
    ),
    // ===== ARCADE =====
    SystemModel(
      id: 'arcade',
      name: 'Arcade',
      manufacturer: 'Various',
      releaseYear: 1978,
      isZipped: true,
      libretroId: 'MAME',
      romExtensions: ['.zip'],
      iconName: 'arcade.svg',
      accentColor: Color(0xFFF59E0B),
      raConsoleId: 27,
    ),
    // ===== DOS =====
    SystemModel(
      id: 'dos',
      name: 'DOS',
      manufacturer: 'Microsoft',
      releaseYear: 1981,
      isZipped: true,
      libretroId: 'DOS',
      romExtensions: ['.zip', '.dosz', '.exe', '.com', '.bat'],
      iconName: 'ms-dos.svg',
      accentColor: Color(0xFF9CA3AF),
      raConsoleId: 26,
    ),
    // ===== SCUMMVM =====
    // Point-and-click adventures. Each game is a folder of data files
    // (MONKEY.000, TENTACLE.001, *.LA0, ...), kept as a folder on download.
    SystemModel(
      id: 'scummvm',
      name: 'ScummVM',
      manufacturer: 'LucasArts, Sierra & more',
      releaseYear: 1987,
      isZipped: false,
      libretroId: 'ScummVM',
      romExtensions: ['.scummvm', '.svm'],
      multiFileExtensions: [
        '.000', '.001', '.la0', '.la1', '.lfl', '.sou', '.he0', '.he1',
        '.rsc', '.cat', '.map', '.dat', '.exe', '.scummvm', '.svm',
      ],
      iconName: 'scummvm.svg',
      accentColor: Color(0xFF7BC043),
    ),
    // ===== NINTENDO =====
    SystemModel(
      id: 'gameandwatch',
      name: 'Game & Watch',
      manufacturer: 'Nintendo',
      releaseYear: 1980,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_and_Watch',
      romExtensions: ['.mgw'],
      iconName: 'handheld_game_and_watch.svg',
      accentColor: Color(0xFFA16207),
      raConsoleId: 60,
    ),
    // ===== FANTASY =====
    SystemModel(
      id: 'tic80',
      name: 'TIC-80',
      manufacturer: 'Nesbox',
      releaseYear: 2017,
      isZipped: false,
      libretroId: 'TIC-80',
      romExtensions: ['.tic'],
      iconName: 'tic-80.svg',
      accentColor: Color(0xFFEC4899),
      raConsoleId: 65,
    ),
    SystemModel(
      id: 'pico8',
      name: 'PICO-8',
      manufacturer: 'Lexaloffle',
      releaseYear: 2015,
      isZipped: false,
      libretroId: '',
      romExtensions: ['.p8'],
      iconName: 'pico-8.svg',
      accentColor: Color(0xFFEC4899),
    ),
  ];

  /// Archive formats that may wrap ROM files.
  static const archiveExtensions = ['.zip', '.7z', '.rar'];

  /// Union of all romExtensions across every supported system.
  static final Set<String> allRomExtensions = {
    for (final s in supportedSystems) ...s.romExtensions,
  };

  /// All file extensions that represent game files (ROMs + archives + multi-file parts).
  static final Set<String> allGameExtensions = {
    ...archiveExtensions,
    ...allRomExtensions,
    for (final s in supportedSystems)
      if (s.multiFileExtensions != null) ...s.multiFileExtensions!,
  };

  /// Whether [name] ends with a known game file extension.
  static bool isGameFile(String name) {
    final lower = name.toLowerCase();
    return allGameExtensions.any((ext) => lower.endsWith(ext));
  }
}
